In [1]:
import os
import time
import datetime
import json
from glob import glob

#import matplotlib for visualization
import matplotlib.pyplot as plt
%matplotlib_inline
from IPython.display import set_matplotlib_formats

# import torch 
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torchvision.datasets import datasets
from torch.utils.datasets import transforms
from matplotlib_colors import _rgba
import seaborn as sns
sns.set()
from tqdm.notebook import tqdm
import tensorboard


UsageError: Line magic function `%matplotlib_inline` not found.


In [2]:
import torch
print(torch.__version__)

2.8.0+cpu


In [3]:
torch.manual_seed(45)

In [4]:
x = torch.tensor(2)
print(x)

tensor(2)


In [5]:
x = torch.ones(3, 7, 8)
print(x)

tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]])


In [6]:
x = torch.zeros(3, 9, 0)
print(x)

tensor([], size=(3, 9, 0))


In [7]:
x = torch.Tensor(4, 8, 9)
print(x)

tensor([[[1.6398e-30, 1.8035e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.000

In [8]:
x = torch.ones(3, 9, 3)
print(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [9]:
u = torch.rand(5, 8, 9)
print(u)

tensor([[[1.8695e-01, 9.6133e-01, 6.8345e-01, 8.9880e-01, 5.0508e-02,
          5.5546e-01, 7.8613e-01, 5.6623e-02, 7.8419e-01],
         [1.4798e-01, 3.8841e-02, 1.0374e-01, 4.2163e-01, 2.3734e-01,
          8.1106e-01, 5.3401e-01, 6.8338e-01, 6.5282e-01],
         [6.1227e-01, 9.8335e-01, 1.8260e-01, 1.2392e-01, 4.2622e-01,
          9.7167e-01, 6.2475e-01, 7.8219e-01, 4.0979e-01],
         [3.4706e-01, 2.8339e-01, 7.5210e-01, 3.6280e-01, 6.2434e-01,
          8.5685e-01, 7.9121e-01, 3.0541e-01, 3.7614e-02],
         [7.7591e-01, 3.1586e-01, 1.5996e-01, 5.8378e-01, 4.8312e-01,
          1.1204e-01, 7.8999e-01, 1.8129e-01, 1.0043e-01],
         [1.6550e-01, 5.0939e-01, 5.7926e-01, 1.4609e-01, 6.6261e-01,
          3.2352e-01, 3.4021e-01, 6.3160e-01, 6.5374e-01],
         [8.2440e-02, 8.9604e-01, 3.2628e-01, 5.3052e-01, 5.7340e-01,
          8.3325e-01, 8.3110e-01, 7.4649e-01, 3.0476e-01],
         [2.4190e-01, 8.5705e-01, 3.4584e-01, 1.3889e-01, 7.6845e-01,
          2.2834e-01, 4.826

In [10]:
x = torch.ones(8)
print(x)

tensor([1., 1., 1., 1., 1., 1., 1., 1.])


In [11]:
i = torch.arange(8)
print(i)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [12]:
x = u.shape
print("shape", u.shape)

shape torch.Size([5, 8, 9])


In [13]:
v =  u.size()
print("size", v)

size torch.Size([5, 8, 9])


In [14]:
w = torch.rand(7, 8, 3)
w

tensor([[[0.3094, 0.6075, 0.8562],
         [0.0399, 0.4041, 0.3686],
         [0.4704, 0.3168, 0.1663],
         [0.2488, 0.6075, 0.4631],
         [0.4786, 0.3076, 0.1119],
         [0.4304, 0.9634, 0.2369],
         [0.2894, 0.1722, 0.0912],
         [0.1056, 0.7096, 0.2609]],

        [[0.7053, 0.4911, 0.7929],
         [0.2301, 0.1367, 0.1564],
         [0.7619, 0.5723, 0.4911],
         [0.4614, 0.6774, 0.1915],
         [0.5507, 0.7793, 0.3747],
         [0.1483, 0.6539, 0.6452],
         [0.7916, 0.7610, 0.9121],
         [0.3661, 0.4697, 0.2300]],

        [[0.0919, 0.4194, 0.1557],
         [0.6062, 0.9720, 0.1754],
         [0.6462, 0.4874, 0.2707],
         [0.6206, 0.7584, 0.9558],
         [0.6159, 0.2043, 0.4921],
         [0.5812, 0.8287, 0.1333],
         [0.7035, 0.4565, 0.8788],
         [0.2918, 0.5051, 0.6804]],

        [[0.3380, 0.0614, 0.4854],
         [0.3306, 0.4069, 0.8966],
         [0.0545, 0.4287, 0.3115],
         [0.3106, 0.1970, 0.8973],
         [0.96

In [15]:
c = w.size()
print("size", c)

size torch.Size([7, 8, 3])


In [16]:
c = w.shape
print("shape", c)

shape torch.Size([7, 8, 3])


In [17]:
import numpy as np
bit = np.array([[3,7], [7,9]])
print(bit)
sit = torch.from_numpy(bit)
print(sit)

[[3 7]
 [7 9]]
tensor([[3, 7],
        [7, 9]])


In [18]:
b = np.array([[[5,8], [4,0], [2,8]]])
u = torch.from_numpy(b)
print(u) ## converting numpy to a torch version

tensor([[[5, 8],
         [4, 0],
         [2, 8]]])


In [19]:
w = torch.arange(8)
v = w.numpy()
print(v)

[0 1 2 3 4 5 6 7]


In [20]:
b = torch.arange(7)
c = b.numpy()
print(c)

[0 1 2 3 4 5 6]


In [21]:
f = np.array([3, 9, 0, 4])
u = torch.from_numpy(f)
print(u)

tensor([3, 9, 0, 4])


In [22]:
## operations in numpy
x = torch.tensor([4,6,9,5])
y = torch.tensor([3,2,6,9])

w = x + y
print(w)

tensor([ 7,  8, 15, 14])


In [23]:
y = torch.add(3,4)
y

tensor(7)

In [24]:
u = torch.tensor([5,6,9])
y = torch.tensor([5,8,3])

h = u + y
print(h)

tensor([10, 14, 12])


In [25]:
o = torch.add(4,5)
o

tensor(9)

In [26]:
y = torch.sub(6,7)
y

tensor(-1)

In [27]:
i = torch.sub(9,4)
i

tensor(5)

In [28]:
u = torch.tensor([[3,6], [4, 8]])
v = torch.tensor([[4,9], [2, 4]])

s = v + u
print("s before", s)

u.add_(v)
print("u after the value", v)

s before tensor([[ 7, 15],
        [ 6, 12]])
u after the value tensor([[4, 9],
        [2, 4]])


In [29]:
v = torch.tensor([[[4, 8, 9], [3, 0, 8], [3, 8, 7]]])
v

tensor([[[4, 8, 9],
         [3, 0, 8],
         [3, 8, 7]]])

In [30]:
i = torch.rand(8, 8)
x = torch.rand(8, 8)

c = x + i
print(c)

tensor([[1.1903, 0.6903, 0.5634, 1.2376, 0.8952, 1.0030, 1.8961, 0.8896],
        [1.3633, 0.3895, 1.2584, 1.2516, 0.9177, 0.8382, 0.2206, 1.1689],
        [1.3421, 1.4666, 0.5974, 0.7897, 0.4270, 0.9850, 1.3147, 0.5055],
        [0.9045, 1.3342, 1.0755, 1.6828, 1.2247, 0.5098, 1.2006, 0.3646],
        [1.4721, 0.6023, 1.1542, 1.2935, 1.6566, 1.3171, 1.1050, 0.8157],
        [1.6635, 0.8927, 1.8562, 0.7718, 0.7430, 1.1774, 0.8087, 1.7715],
        [0.1212, 1.1007, 0.4314, 0.9633, 1.0797, 0.5741, 1.7988, 1.4660],
        [0.9507, 1.1752, 1.3196, 0.9745, 0.8555, 0.6925, 0.8043, 0.3454]])


In [31]:
i.add_(x)

tensor([[1.1903, 0.6903, 0.5634, 1.2376, 0.8952, 1.0030, 1.8961, 0.8896],
        [1.3633, 0.3895, 1.2584, 1.2516, 0.9177, 0.8382, 0.2206, 1.1689],
        [1.3421, 1.4666, 0.5974, 0.7897, 0.4270, 0.9850, 1.3147, 0.5055],
        [0.9045, 1.3342, 1.0755, 1.6828, 1.2247, 0.5098, 1.2006, 0.3646],
        [1.4721, 0.6023, 1.1542, 1.2935, 1.6566, 1.3171, 1.1050, 0.8157],
        [1.6635, 0.8927, 1.8562, 0.7718, 0.7430, 1.1774, 0.8087, 1.7715],
        [0.1212, 1.1007, 0.4314, 0.9633, 1.0797, 0.5741, 1.7988, 1.4660],
        [0.9507, 1.1752, 1.3196, 0.9745, 0.8555, 0.6925, 0.8043, 0.3454]])

In [32]:
i = torch.tensor([3, 9, 0, 7])
u = torch.tensor([9, 3, 8, 9])

w = i + u
print(w)

tensor([12, 12,  8, 16])


In [33]:
i.add_(u)

tensor([12, 12,  8, 16])

In [34]:
x = torch.arange(6)
print(x)

tensor([0, 1, 2, 3, 4, 5])


In [35]:
x  = x.view(2,3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [36]:
x = torch.arange(9)
print(x)
x = x.view(3,3)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [37]:
x = torch.arange(8)
x = x.view(4, 2)
x               ## view is use for changing shape or reshaping values

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [38]:
x = x.permute(1,0)
x

tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])

In [39]:
x = x.permute(0, 1)
x

tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])

In [40]:
b = torch.arange(9).view(3,3)
print(b)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [41]:
g = torch.arange(10).view(2, 5)
print(g)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [42]:
c = torch.arange(6).view(3, 2)
print(c)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [43]:
u = torch.arange(6).view(2,3)
u

tensor([[0, 1, 2],
        [3, 4, 5]])

In [44]:
y = torch.arange(9).view(3,3)
y

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [45]:
x = u @ y
x

tensor([[15, 18, 21],
        [42, 54, 66]])

In [46]:
x = torch.matmul(u, y)
x

tensor([[15, 18, 21],
        [42, 54, 66]])

In [47]:
## indexing in pytoch
x = torch.arange(10).view(2, 5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [48]:
x = x[:, 2]
x

tensor([2, 7])

In [49]:
d = torch.arange(6).view(2, 3)
d


tensor([[0, 1, 2],
        [3, 4, 5]])

In [50]:
print(d[0:, 2])

tensor([2, 5])


In [51]:
print(d[1:, 1])

tensor([4])


In [52]:
x = torch.ones(9)
print(x.requires_grad)

False


In [53]:
u = torch.zeros(7)
print(u.requires_grad)

False


In [54]:
x.requires_grad_(True)
print(x.requires_grad)

True


In [55]:
u.requires_grad_(True)
print(u.requires_grad)

True


In [56]:
x = torch.ones(3, requires_grad = True, dtype = torch.float32)
x

tensor([1., 1., 1.], requires_grad=True)

In [57]:
a = x + 2
b = a ** 2
c = b + 3
y = c.mean()
print("Y", y)

Y tensor(12., grad_fn=<MeanBackward0>)


In [58]:
v = torch.arange(6, requires_grad = True, dtype = torch.float32)
v

tensor([0., 1., 2., 3., 4., 5.], requires_grad=True)

In [59]:
a = v + 2
b = a ** 2
c = b + 4
y = c.mean()
print("Y", y)

Y tensor(27.1667, grad_fn=<MeanBackward0>)


In [60]:
y.backward()

In [61]:
print(v.grad)

tensor([0.6667, 1.0000, 1.3333, 1.6667, 2.0000, 2.3333])


In [62]:
print(x.grad)

None


In [63]:
gpu_avail = torch.cuda.is_available()
print(f"is the gpu_available? {gpu_avail}")

is the gpu_available? False


In [64]:
device = torch.device("cuda") if torch.cuda.is_available()else torch.device("cpu")
print("Device", device)

Device cpu


In [65]:
device = torch.device("cuda") if torch.cuda.is_available()else torch.device("cpu")
print("Device", device)

Device cpu


In [66]:
x = torch.zeros(7)
x = x.to(device)
print("X", x)

X tensor([0., 0., 0., 0., 0., 0., 0.])


In [67]:
device = torch.device("cuda") if torch.cuda.is_available()else torch.device("cpu")
print("Device", device)

Device cpu


In [68]:
y = torch.zeros(8)
x = y.to(device)
print("x", x)

x tensor([0., 0., 0., 0., 0., 0., 0., 0.])


In [69]:
x = torch.ones(500, 500)
start_time = time.time()
_ = torch.matmul(x, x)
end_time = time.time()

print(f"cpu time :{(end_time - start_time):6.5f}s")
print(f"CPU time: {(end_time - start_time):6.5f}s")

cpu time :0.00221s
CPU time: 0.00221s


In [70]:
x = torch.ones(12,12)
start_time = time.time()
_ = torch.matmul(x, x)
end_time = time.time()

print(f"cpu time :{(end_time - start_time):6.5f}s")

cpu time :0.00042s


In [71]:
v = torch.ones(400, 400)
start_time = time.time()
_ = torch.matmul(v,v)
end_time = time.time()

print(f"the cpu time is {(end_time - start_time):6.5f}s")

the cpu time is 0.00115s


In [72]:
x = x.to("device")
_ = torch.matmul(x, x)

start  = start.cuda.Event(starting_time = True)
end    = end.cuda.Event(ending_time = True)

start_record()
_ = torch.matmul(x, x)

end_record()

print(f" the gpu :{(0.0001 * start_elpased_time(end)):6.5f}s")

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, maia, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: device

In [84]:
import torch.nn as nn

In [85]:
class MyModule(nn.Module):
    def __init__(self, num_input, hidden_layer, num_output):
        super().__init__()

        self.linear1 = nn.Linear(num_input, hidden_layer)
        self.act_fn = nn.Tanh()
        self.linear2 = nn.Linear(hidden_layer, num_output)

    def forward(self,x):
        x = self.linear1(x)
        x = self.act_fn(x)
        x = self.linear2(x)

        return x

In [86]:
module = MyModule(num_input = 3, hidden_layer = 4, num_output = 5)
print("module", module)

module MyModule(
  (linear1): Linear(in_features=3, out_features=4, bias=True)
  (act_fn): Tanh()
  (linear2): Linear(in_features=4, out_features=5, bias=True)
)


In [87]:
class Mymodules(nn.Module):
    def __init__(self, num_input, num_hidden, num_output):
        super().__init__()

        self.linear1 = nn.Linear(num_input, num_hidden)
        self.activate = nn.Tanh()
        self.linear2 = nn.Linear(num_hidden, num_output)

    def forward(self, x):
        x = self.linear1(x)
        x = self.activate(x)
        x = self.linear2(x)

        return x

In [88]:
module = Mymodules(num_input = 3, num_hidden = 4, num_output = 7)
print("module", module)

module Mymodules(
  (linear1): Linear(in_features=3, out_features=4, bias=True)
  (activate): Tanh()
  (linear2): Linear(in_features=4, out_features=7, bias=True)
)


In [89]:
import torch.nn.functional as F

In [90]:
for name, params in module.named_parameters():
    print(f" parameters {name}, shape {params.shape} ") 

 parameters linear1.weight, shape torch.Size([4, 3]) 
 parameters linear1.bias, shape torch.Size([4]) 
 parameters linear2.weight, shape torch.Size([7, 4]) 
 parameters linear2.bias, shape torch.Size([7]) 


In [91]:
for name, params in module.named_parameters():
    print(f"parameter {name}, shape {params.shape}")

parameter linear1.weight, shape torch.Size([4, 3])
parameter linear1.bias, shape torch.Size([4])
parameter linear2.weight, shape torch.Size([7, 4])
parameter linear2.bias, shape torch.Size([7])


In [92]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [93]:
import torch.utils.data as data

In [94]:
class Data(data.Dataset):
    def __init__(self, books, size, std = 0.004):
        super().__init__()

        self.books = books
        self.size = size
        self.std = std
        self.generate.continous_xor_()


    def generate_continous_xor(self):


        data = torch.randint(high = 2, low = 0, size = (self.size, 2), dtype = torch.float32)
        label = (data.sum(dim=1) ==1).to(torch.long)

        self.data = data
        self.label = label

    def __len__(self):
        return self.size


    def __getitem__(self, idx):
        data_point = self.data[idx]
        data_label = self.label[idx]

        return data_point, data_label


In [95]:
import torch.utils.data as data
from PIL import Image
import os


class IMAGELOADER_FILES(Dataset):
    def __init__(self, root_dir, labels, transforms = None):
        self.root_dir = root_dir
        self.labels = labels
        self.image_files = list(labels.keys())
        self.transform = transform

    def __len__(self):
        return self.image.files


    def __getitem__(self, index):
        image_files = os.path.join(self.image_files[index], self.root_dir)
        image = image.open(image_files). convert("RGB")
        label = self.labels[self.image_files[idx]]

        return image, label
        

In [96]:
class MultimodalDataset(Dataset):
    def __init__(self, images, text, tokenizer, transform):
        self.images = images
        self.text = text
        self.tokenizer = tokenizer
        self.transform = transform

    def __getitems__(self, indx):
        images = self.transform(image.open.files(self.images[idx]))
        tokenizer = self.tokenizer(
            self.text[idx],
            paddings = "max_length",
            truncations = True,
            return_tensor = "pt"
        )

        return {
            "images": images,
            "out_put": tokenizer["out_put"].unsqueeze(0),    
            "attention_map": tokenizer["attention_map"].unsqueeze(0)
        }

    def __len__(self):
        return len(self.images)
        
        

In [97]:
class Custom(Dataset):
    def __init__(self,images, labels):
        self.images = images
        self.labels = labels

    def __getitem__(self, idx):
        labels = self.labels[idx]
        images = self.images[idx]

        return labels, images

    def __len__(self):
        return len(self.images)

In [98]:
images = list(range(200))
labels = list(range(500))

customs = Custom(images = images, labels = labels)
print("the customs shapes", len(customs))
print("the data points 0 is ", customs[0])

the customs shapes 200
the data points 0 is  (0, 0)


In [99]:
import torch.utils.data as data
from torch.utils.data import DataLoader, Dataset

loader = DataLoader(
    customs,
    batch_size = 40,
    shuffle = True
)

loader

images, labels = next(iter(loader))

print("images shapes", images.shape)
print("label shapes", labels.shape)

images shapes torch.Size([40])
label shapes torch.Size([40])


In [100]:
import os
from PIL import Image
import torch
import torch.utils.data as data
from torch.utils.data import DataLoader, Dataset
import torchvision.transforms as T

In [101]:
import os
from PIL import Image
import torch
import torchvision.transforms as T
from torch.utils.data import DataLoader, Dataset
import torchvision

In [102]:
class Category(Dataset):
    def __init__(self, root_dir, transform = None):
        self.root_dir = root_dir
        self.transform = transform
        self.samples  = []


        for label, images in enumerate(["cat", "dog"]):
            class_path = os.path.join(root_dir, images)
        for img_name in os.listdir(class_path):
            self.samples.append((os.path.join(class_path, img_name) , label))

    def __getitem__(self, index):
        img_name, label = self.samples[index]
        image = Image.open(img_name).convert("RGB")

        if self.transform:
           image = self.transform(image)

        return image, label

    def __len__(self):
        return len(self.samples)
    

In [103]:
import torchvision.transforms as T
from torch.utils.data import DataLoader, Dataset

In [104]:
import torch.nn.functional as F
import torchvision
import torchvision.transforms as T
from PIL import Image

transforms = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor()
])

dataset = Category("dataset/train", transform=transforms)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

images, label = next(iter(loader))
print(images.shape)   # [32, 3, 224, 224]
print(label.shape)


    
    
    

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dataset/train\\dog'

In [105]:
Loss = nn.BCEWithLogitsLoss()
Loss

BCEWithLogitsLoss()

In [106]:
loss = nn.BCELoss()
loss

BCELoss()

In [107]:
optimizer = torch.optim.SGD(module.parameters(), lr = 0.004)

In [108]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.004
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [109]:
from torch.utils.data import DataLoader

In [110]:
train_dataset = Custom(labels = labels, images = images)
train_data_loader = DataLoader(
    train_dataset,
    batch_size = 40,
    shuffle = True
)
train_data_loader

In [111]:
module.to(device)

Mymodules(
  (linear1): Linear(in_features=3, out_features=4, bias=True)
  (activate): Tanh()
  (linear2): Linear(in_features=4, out_features=7, bias=True)
)

In [112]:
print(dir(data))

['BatchSampler', 'ChainDataset', 'ConcatDataset', 'DFIterDataPipe', 'DataChunk', 'DataLoader', 'Dataset', 'DistributedSampler', 'IterDataPipe', 'IterableDataset', 'MapDataPipe', 'RandomSampler', 'Sampler', 'SequentialSampler', 'StackDataset', 'Subset', 'SubsetRandomSampler', 'TensorDataset', 'WeightedRandomSampler', '_DatasetKind', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_utils', 'argument_validation', 'dataloader', 'datapipes', 'dataset', 'default_collate', 'default_convert', 'distributed', 'functional_datapipe', 'get_worker_info', 'graph', 'graph_settings', 'guaranteed_datapipes_determinism', 'non_deterministic', 'random_split', 'runtime_validation', 'runtime_validation_disabled', 'sampler']


In [115]:
! pip install tqdm

In [116]:
def train_model(module, optimizer, train_dataset, loss, num_epochs = 300):
    module.train()


    # Training the loop
    for epoch in tqdm(range(num_epochs)):
        images, labels in loader

        data_images = images.to("device").float()
        data_labels = labels.to("device").float()

    #  step 2: calculating the prediction 

        preds = module(data_images)
        preds = preds.squeeze(dim = 1)

   # step 3 : calculating the loss function

        loss = Loss(preds, data_labels)

  # step 4 : before calculating the gradient descent we have to scale the optimizer value to zero

        optimizer.zero_grad()
  # step 5 : calculate the backward propagation

        loss.backward()

   # step 6 : update the parameters of those values

        optimizer.step()










    
        

In [123]:
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

def train_model(module, optimizer, train_dataset, loss_fn, batch_size=32, num_epochs=300):
    # Device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    module.to(device)
    module.train()
    
    # Create DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    
    for epoch in tqdm(range(num_epochs), desc="Training Epochs"):
        epoch_loss = 0.0
        
        for images, labels in train_loader:
            # Move to device
            images = images.to(device).float()
            labels = labels.to(device).float()

            # Step 2: forward pass
            preds = module(images)
            if preds.shape != labels.shape:
                preds = preds.squeeze(dim=1)  # adjust shape if needed

            # Step 3: calculate loss
            loss = loss_fn(preds, labels)

            # Step 4: zero gradients
            optimizer.zero_grad()

            # Step 5: backward pass
            loss.backward()

            # Step 6: update parameters
            optimizer.step()

            epoch_loss += loss.item() * images.size(0)
        
        avg_loss = epoch_loss / len(train_loader.dataset)
        print(f"Epoch [{epoch+1}/{num_epochs}] - Loss: {avg_loss:.4f}")
    
    print("Training finished.")
